#!/usr/bin/env bash

CHG=$(acpi -b | sed -e "s/^.* \([^ ]*\)%.*$/\1/")

if [ $CHG -lt 15 ] && [ $(acpi -b | grep -ic charging) -eq 0 ]
then
    DISPLAY=:0.0 /usr/bin/notify-send -u critical "battery low ($CHG%)!" "\n$(acpi -b)"
fi
