#!/usr/bin/env bash
#
# crontab :
# 0,10,20,30,40,50 * * * * /usr/bin/battery_warning


CHG=$(acpi -b | sed -e "s/^.* \([^ ]*\)%.*$/\1/")

if [ $CHG -lt 10 ]
then
    DISPLAY=:0.0 /usr/bin/notify-send -u critical "battery low ($CHG%)!" "\n$(acpi -b)"
fi
