#!/usr/bin/env bash

brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

if [ $brightness -gt 0 ]
then
    brightness=$(($brightness-100))

    if [ $brightness -lt 0 ]
    then
        brightness=0
    fi

    echo "echo $brightness > /sys/class/backlight/intel_backlight/brightness" | sudo zsh
fi
