#!/usr/bin/env bash

max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

echo "echo $max_brightness > /sys/class/backlight/intel_backlight/brightness" | sudo sh
