#!/usr/bin/env zsh

feature=${1:?"Syntax $0 <feature file>"}

stepCounter=0
x=$(egrep -c "Given|When|Then|And" $feature)
stepCounter=$((stepCounter+x))

exampleSteps=0
scenarios=0

fileLength=$(wc -l $feature | awk '{print $1}')
inOutline=""
currLine=0

cat $feature | while read line
do
  currLine=$((currLine + 1))
  if [ $(echo "$line" | grep -c "Scenario Outline") -gt 0 ]
  then
    inOutline="y"
    testCount=0
    exampleCount=0
  fi
  
  [ "$inOutline" ] && [ $(echo "$line" | egrep -c "Given|When|Then|And") -gt 0 ] && testCount=$((testCount+1))

  [ $(echo "$line" | grep -c "|") -gt 0 ] && exampleCount=$((exampleCount + 1))

  if [ $(echo "$line" | grep -c "Scenario:") -gt 0 ] || [ $currLine -eq $fileLength ]
  then
    if [ "$inOutline" ]
    then
      # (we already counted these steps once, we just want any 'repeats' from outlines)
      exampleCount=$((exampleCount-1))
      thisOutlineCount=$((testCount * exampleCount))

      exampleSteps=$((exampleSteps + thisOutlineCount))
      scenarios=$((scenarios + testCount))
    else
      scenarios=$((scenarios + 1))
    fi

    inOutline=""
  fi
done

totalCount=$((stepCounter + exampleSteps))

echo """
$feature
SCENARIOS: $scenarios
STEPS    : $totalCount
"""
