#!/usr/bin/env bash

docker pull dlsniper/docker-intellij

docker run -tdi \
           --net="host" \
           --privileged=true \
           -e DISPLAY=${DISPLAY} \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v ${HOME}/.IdeaIC2016.1_docker:/home/developer/.IdeaIC2016.1 \
           -v ${HOME}/go:/home/developer/go \
           dlsniper/docker-intellij
