#!/bin/zsh

printf "\nDEVICES:\n\n$(v4l2-ctl --list-devices)\n\n"

CAMERA=""
IN_CAMERA=""
v4l2-ctl --list-devices | while read line
do
	if [ $(echo "$line" | grep -c "C920") -gt 0 ]
	then
		IN_CAMERA="Y"
		continue
	fi

	if [ "$IN_CAMERA" ]
	then
		CAMERA="$line"
		break
	fi
done

printf "\nCamera device chosen: \"$CAMERA\"\n"

v4l2-ctl -d $CAMERA \
	-c brightness=190 \
	-c sharpness=145 \
	-c saturation=145 \
	-c power_line_frequency=1 \
	-c exposure_auto=1 \
	-c exposure_absolute=128


printf "\nSETTINGS:\n$(v4l2-ctl -l)\n\n"
